# ID, Description, Start Byte, Start Bit, End Byte, End Bit, Type, Coficient, Operator, Unit, Value, Name
LookUp = [["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "0", "Normal"],
["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "1", "Reserved"],
["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "2", "System Error"],
["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "3", "Reserved"],
["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "4", "Reserved"],
["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "5", "Reserved"],
["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "6", "Reserved"],
["40F", "TPMS System Status", "0", "0", "0", "2", "option", "", "", "", "7", "Reserved"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "0", "Rear Right"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "1", "Front Right"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "2", "Rear Left"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "3", "Front Left"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "4", "Reserved"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "5", "Reserved"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "6", "Reserved"],
["40F", "The ID of Tire", "0", "4", "0", "6", "option", "", "", "", "7", "Reserved"],
["40F", "The Tire Information", "0", "7", "0", "7", "option", "", "", "", "0", "Normal"],
["40F", "The Tire Information", "0", "7", "0", "7", "option", "", "", "", "1", "Abnormal"],
["40F", "The Tire Leakage", "1", "0", "1", "1", "option", "", "", "", "0", "Normal"],
["40F", "The Tire Leakage", "1", "0", "1", "1", "option", "", "", "", "1", "Quick Leak"],
["40F", "The Tire Leakage", "1", "0", "1", "1", "option", "", "", "", "2", "Reserved"],
["40F", "The Tire Leakage", "1", "0", "1", "1", "option", "", "", "", "3", "Reserved"],
["40F", "The Tire Learning Status", "1", "2", "1", "3", "option", "", "", "", "0", "Not Learned"],
["40F", "The Tire Learning Status", "1", "2", "1", "3", "option", "", "", "", "1", "Learning"],
["40F", "The Tire Learning Status", "1", "2", "1", "3", "option", "", "", "", "2", "Learn Completed"],
["40F", "The Tire Learning Status", "1", "2", "1", "3", "option", "", "", "", "3", "Learning Failure"],
["40F", "The Tire Pressure Status", "1", "4", "1", "5", "option", "", "", "", "0", "Normal"],
["40F", "The Tire Pressure Status", "1", "4", "1", "5", "option", "", "", "", "1", "Over Pressure"],
["40F", "The Tire Pressure Status", "1", "4", "1", "5", "option", "", "", "", "2", "Under Pressure"],
["40F", "The Tire Pressure Status", "1", "4", "1", "5", "option", "", "", "", "3", "Reserved"],
["40F", "The Tire Temperature Status", "1", "6", "1", "7", "option", "", "", "", "0", "Normal"],
["40F", "The Tire Temperature Status", "1", "6", "1", "7", "option", "", "", "", "1", "Reserved"],
["40F", "The Tire Temperature Status", "1", "6", "1", "7", "option", "", "", "", "2", "High Temperature"],
["40F", "The Tire Temperature Status", "1", "6", "1", "7", "option", "", "", "", "3", "Reserved"],
["40F", "The Tire Pressure", "2", "0", "2", "7", "scalar", "1.3725", "*", " kPa", "", ""],      
["40F", "The Tire Temperature", "3", "0", "3", "7", "scalar", "40", "-", " C", "", ""],
["40F", "The Tire Battery Power Status", "4", "0", "4", "7", "option", "", "", "", "0", "Normal"],
["40F", "The Tire Battery Power Status", "4", "0", "4", "7", "option", "", "", "", "1", "Low Power"],
["40F", "The Tire Battery Power Status", "4", "0", "4", "7", "option", "", "", "", "2", "Reserved"],
["40F", "The Tire Battery Power Status", "4", "0", "4", "7", "option", "", "", "", "3", "Reserved"]]